
document.write('<head>');
document.write('  <style>');
document.write('  td {font-size:14px;font-family:arial,helvetica,sans-serif;}');
document.write('  </style>');
document.write('  <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />');
document.write('  <meta name="description" content="Kwik EFIS for Android devices" />');
document.write('  <meta name="keywords" content="android app, android, homebuilt aircraft, HUD, EFIS, glass cockpit" />');
document.write('  <meta name="robots" content="index,follow">');
document.write('  <title>Kwik EFIS - Electronic Flight Information System for Android</title>');
document.write('</head>');
document.write('<body bgcolor="#FFFFFF" link="#0000FF" vlink="#800080">');
document.write('  <table border="0" cellpadding="2" cellspacing="10" width="600">');
document.write('    <tr>');
document.write('      <td valign="top">');
document.write('        <table border="0" cellspacing="9" width=180>');
document.write('          <tr>');
document.write('            <td valign="top">');
document.write('              <img src="img/goomie_logo.png" alt="kwik logo" width="50"  name="Graphic1"></td>');
document.write('          </tr>');
document.write('          <tr>');
document.write('            <td valign="top" rowspan="5" width="173">');
document.write('              <br/>');
document.write('              <a href="index.html">home</a><br>');
document.write('              <a href="about.html">about</a><br>');
document.write('              <br/>');
document.write('              <!-- <a href="news.html">news</a><br> -->');
document.write('              <a href="gallery.html">gallery</a><br>');
document.write('              <br/>');
document.write('              <a href="installation.html">instructions</a><br>');
document.write('              <a href="faq.html">faq</a><br>');
document.write('              <br/>');
document.write('              <a href="download.html">download / install</a><br>');
document.write('              <br/>');
document.write('              <a href="mailto:ninelima@yahoo.com">contact</a><br>');
document.write('              <!-- <a href="thanks.html">thanks</a><br> -->');
document.write('              <!-- <a href="links.html">links</a><br> -->');
document.write('              <a href="disclaimer.html">disclaimer</a><br>');
document.write('              <br/>');
document.write('                <address>');
document.write('                  <a href="about.html">the Kwik design team</a><br>');
document.write('                </address>');
document.write('              </p>');
document.write('            </td>');
document.write('          </tr>');
document.write('        </table>');
document.write('      </td>');
document.write('      <!-- break bar -->');
document.write('      <td bgcolor="#008080">');
document.write('        <!--&nbsp;-->');
document.write('      </td>');
document.write('      <td valign="top">');
document.write('        <table border="0" width="600">');
document.write('          <tr>');
document.write('            <td>');
document.write('              <h1>');
document.write('                the Kwik EFIS</h1>');
document.write('            </td>');
document.write('          </tr>');
document.write('          <td bgcolor="#99CCFF">');

